export enum Sex {
  MALE = "MALE",
  FEMALE = "FEMALE"
}

export enum InterestField {
  SPORT = "SPORT",
  ENGLISH = "ENGLISH",
  CHINESE = "CHINESE",
  COOKING = "COOKING",
  DEVELOPMENT = "DEVELOPMENT",
  MARKETING = "MARKETING",
  LOVE_RELATIONSHIP = "LOVE_RELATIONSHIP",
  WINE = "WINE",
  BEER = "BEER"
}

export enum PaymentType {
  CHARGE = "CHARGE",
  CHARGE_CANCEL = "CHARGE_CANCEL"
}
